// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSkrqeA_7xybnJzwF1m4I0L84sdqtkRb4',
    appId: '1:321228066325:android:8e67cee110c3c3431c481c',
    messagingSenderId: '321228066325',
    projectId: 'appswhat-2',
    storageBucket: 'appswhat-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-YQvQgbbYnsiu3UE2HfPA8xfVbPA10HU',
    appId: '1:321228066325:ios:caf0b2857d606ac81c481c',
    messagingSenderId: '321228066325',
    projectId: 'appswhat-2',
    storageBucket: 'appswhat-2.appspot.com',
    androidClientId: '321228066325-ki49176ctmn9lejtjk1kfc66sauevld1.apps.googleusercontent.com',
    iosClientId: '321228066325-udg7fcjened6ml20bsrem88ada8mmb7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatChat',
  );
}
